# Generated by Django 3.0.5 on 2020-06-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('action', 'Action'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], default='1', max_length=7)),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('hindi', 'HINDI')], default='1', max_length=7)),
                ('status', models.CharField(choices=[('RA', 'RECRNTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], default='1', max_length=2)),
                ('cast', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
